### ISSUE TITLE
Filter by ranked is not working.

### ISSUE THREAD

**Issue by DooMMasteR** [halsafar/BeatSaberSongBrowser#105]
I can filter unranked songs, no issue at all, but filtering ranked songs, nothing else, just returns an empty list.

Can I do anything to debug the issue?

**Comment by WesVleuten** [comment]
This issue was just fixed server side. Can you confirm it is working again? You only need to restart beatsaber no need for an update.

**Comment by DooMMasteR** [comment]
just like in RIGHT now, nope cannot check but literally the moment I wrote the issue I started playing and it was still broken for me.
